# Generated by Django 4.2.9 on 2024-02-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noticia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticia",
            name="artigo",
            field=models.TextField(max_length=255, verbose_name="Artigos"),
        ),
    ]
