# Generated by Django 5.0.1 on 2024-01-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cadastro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("idade", models.IntegerField()),
                ("sexo", models.CharField(max_length=1)),
                ("cpf", models.CharField(max_length=11)),
                ("profissao", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
            ],
        ),
    ]
