# Generated by Django 4.2.9 on 2024-01-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastro",
            name="profissao",
            field=models.CharField(
                choices=[
                    ("todos", "Todos"),
                    ("anestesista", "Anestesista"),
                    ("cirurgião", "Cirurgiao"),
                    ("clinico geral", "Clinico Geral"),
                ],
                max_length=20,
                verbose_name="Profissão",
            ),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="sexo",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino")],
                max_length=20,
                verbose_name="Sexo",
            ),
        ),
    ]
