# Generated by Django 4.2.9 on 2024-01-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_cadastro_profissao_alter_cadastro_sexo"),
    ]

    operations = [
        migrations.AddField(
            model_name="cadastro",
            name="cadastrado_em",
            field=models.DateTimeField(auto_now=True, verbose_name="Cadastrado em"),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="cpf",
            field=models.CharField(max_length=11, verbose_name="CPF"),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="email",
            field=models.CharField(max_length=200, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="idade",
            field=models.IntegerField(verbose_name="Idade"),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="nome",
            field=models.CharField(max_length=200, verbose_name="Nome"),
        ),
    ]
